### ISSUE TITLE
Ajouter une mise en forme sur le masquage des sujets épinglés

### ISSUE THREAD

**Issue by Lauloque** [L0Lock/OCTweaksScript#1]
## Problème :
- Le bouton de masquage des sujets épinglés est un peu trop discret.
- Il ne communique pas clairement son action ni son état

## Solution :
Modifier  le label, par exemple "affichage des sujets épinglés", peut-être aussi l'agrandir un peu (et mettre en gras?), ainsi que changer son apparence en fonction de son état :

Comme le fait déjà la boîte a outils des modos, peut-être simplement ajouter "▼" quand les sujets épinglés sont masqués, et "►" lorsqu'ils sont affichés.

![https://i.imgur.com/adwY137.gif](https://i.imgur.com/adwY137.gif)

Sinon, j'avais pensé faire un système de checkbox, check pour "affiché", uncheck pour "masqué". Ou mieux, un petit icone d'oeil grisé ou non, comme dans mes logiciels de 3D pour afficher/masquer des objets.

![https://i.imgur.com/FZa3EpC.gif](https://i.imgur.com/FZa3EpC.gif)

**Comment by benzouye** [comment]
Je pense que le temps que tu postes l'issue, Lame avait modifié l'apparence ... Regarde ce que tu en penses.

**Comment by Lauloque** [comment]
Ah!
Je pense que c'est plutôt la MAJ du script qui ne s'est pas lancée automatiquement. Parceque la dernière modif date d'il y a 9h. ^^

C'est déjà bien mieux, bouton bien lisible et compréhensible. Mais z'en pensez quoi de l'idée de l'icone sinon ? (d'autant plus que tel quel, ça change la largeur du bouton au switch, alors qu'un icone ne le ferait pas)

**Comment by Lamecarlate** [comment]
Ah bin je viens de voir le message (pas de net à la maison, et l'accès à mes mails est compliqué au boulot, du coup je les regarde sur le téléphone et… je les oublie).

Je ne suis pas fan des boutons faits uniquement d'une icône, surtout que celui-ci serait tout seul sur sa ligne, donc bon le gain n'est pas fameux.

Ensuite, je te rejoins sur le fait que la largeur change : on pourrait fixer une largeur minimale relativement grande, suffisante pour que les deux textes y rentrent ? (perso j'ai juste repris les classes des boutons d'OC)

> Je pense que c'est plutôt la MAJ du script qui ne s'est pas lancée automatiquement

Ui, j'oublie trop souvent de changer le numéro de version. Bad cat, bad.

**Comment by benzouye** [comment]
> celui-ci serait tout seul sur sa ligne
On pourrait le placer ailleurs, par exemple à côté du titre du forum, ça fait gagner de la place en plus ...
> Je ne suis pas fan des boutons faits uniquement d'une icône
Moi j'aime bien, il suffirait de trouver une icône assez parlante, genre : 
![display](https://user-images.githubusercontent.com/4947952/41362003-9fa2832e-6f30-11e8-9a5d-787f443e751b.jpg)

**Comment by Lauloque** [comment]
> Je ne suis pas fan des boutons faits uniquement d'une icône, surtout que celui-ci serait tout seul sur sa ligne, donc bon le gain n'est pas fameux.

Pareil. C'est pour ça que j'imagine un label texte qui décrit la fonciton, suivi d'un icone taille fixe qui indique l'état.

D'où viennent ces icones @benzouye ? Est-ce que tu les as en svg ?

**Comment by benzouye** [comment]
Piqué sur le net en .png ...
Je push une version 1.0.4 avec ;)

**Comment by Lauloque** [comment]
t'as check les autorisations d'utilisation ?

**Comment by benzouye** [comment]
Non ... pas bien ... mais maintenant c'est réglé, tu as check les droits sur les tiennes ?

**Comment by Lauloque** [comment]
Je les ai créé moi-même et les cède à l'héritage de l'humanité! 😊

**Comment by benzouye** [comment]
Mais quel talent ... et tant de générosité !

**Comment by Lauloque** [comment]
ET J'EN SUIS FIER PUTAIN !!!!
![](http://i.imgur.com/TLRsvDN.gif)
