### ISSUE TITLE
[Bug] Fix hauteur des messages et pop-up des boutons de gestion

### ISSUE THREAD

**Issue by Lauloque** [L0Lock/OCTweaksScript#2]
En tant que modo, le nombre d'items affichés sur les messages au survol est plus élevé, et prend tellement de place qu'il provoque un retour à la ligne de l'heure de post du message, ainsi qu'un sursaut de hauteur de tout le reste :

![aaaaaaaaaaargh!!!](https://i.imgur.com/dvqGjni.gif)

De plus, modo ou non, je trouve personnellement assez chiant d'avoir des boutons invisibles, certains nouveaux ont du mal à comprendre quoi faire quand on leur dit d'éditer leurs messages, ...

Donc une solution simple et pratique aux deux problèmes pourrait être de faire afficher ces boutons constamment. Sinon, au moins faire en sorte qu'il n'y ait pas ce saut... Je sais pas comment... Je suis noob... Pas taper !!!

**Comment by benzouye** [comment]
Il va être compliqué de forcer l'affichage vu que c'est du JS ...
Rapidement on peut simplement diminuer légèrement la taille de police pour empêcher le retour ...
Lame ? Tu sais si l'on peut intercepter un traitement JS ?

**Comment by Lauloque** [comment]
Ils pouvaient pas faire ça en css3 comme tout le monde ?! :'(

**Comment by Lamecarlate** [comment]
(Bon je sais pas si ce message vous parviendra, je réponds par mail en vitesse, toujours pas le net en dehors du téléphone)

Intercepter, peut-être, si on connaît exactement l'événement. Je regarderai lundi =)

Le 14 juin 2018 18:30:11 UTC+02:00, benzouye <notifications@github.com> a écrit :
>Il va être compliqué de forcer l'affichage vu que c'est du JS ...
>Rapidement on peut simplement diminuer légèrement la taille de police
>pour empêcher le retour ...
>Lame ? Tu sais si l'on peut intercepter un traitement JS ?
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/L0Lock/OCTweaksScript/issues/2#issuecomment-397357365

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Lauloque** [comment]
(@Lamecarlate  reçu!)
