### ISSUE TITLE
Bug d'affichage outil OC de déplacement de topics

### ISSUE THREAD

**Issue by Lauloque** [L0Lock/OCTweaksScript#4]
Lorsqu'on utilise l'outil d'OC pour déplacer un topic, la page est recouverte en bleu mais l'outil de déplacement n'est pas affiché par dessus comme d'habitude.

Ma solution à moi a été de supprimer cette ligne dans l'html de la page:

![demo pic](https://i.imgur.com/DiIxIhA.png)

Ça enlève l'écran bleu, l'outil et la page sont alors à nouveauvisibles.

De toutes façons, pour ma part je déteste quand un outil de modération te cache la page que tu modères.

**Comment by benzouye** [comment]
Je n'observe pas tout à fait le même comportement, dans la mesure où même le script désactivé la modale bleue apparaît au-dessus du formulaire de déplacement ...
Le problème c'est que la modale bleue est ajoutée à la volée ... donc MutationObserver pour détecter son apparition et la supprimer aussitôt ... Allez je corrige cela, mais dans le ModerationScript ;)
